### ISSUE TITLE
link: wrongly displaying links only connected to one node

### ISSUE THREAD

**Issue by hunchback** [skydive-project/skydive-ui#1]
![image](https://user-images.githubusercontent.com/2760739/68541811-b12d0f80-03ac-11ea-9146-0cae4581ba46.png)

**Comment by hunchback** [comment]
![image](https://user-images.githubusercontent.com/2760739/68541835-0537f400-03ad-11ea-8ef5-d1d8fbe2707a.png)

**Comment by hunchback** [comment]
the problem is that when a link connects between a node displayed and a node not displayed we get a link pointing from the visible node to the top of the screen. The expected behavior is that a link which is connected to a node not visible is not visible.

**Comment by safchain** [comment]
would you be able to share a topology dump ?

**Comment by safchain** [comment]
can you share a topology dump please ?

**Comment by hunchback** [comment]
[dump.json.txt](https://github.com/skydive-project/skydive-ui/files/3836182/dump.json.txt)

**Comment by safchain** [comment]
thanks

**Comment by safchain** [comment]
Should be fix: https://github.com/skydive-project/skydive-ui/commit/8854e12f1c3109c7a2747256a74049f710b7d4a6

**Comment by hunchback** [comment]
![image](https://user-images.githubusercontent.com/2760739/68844165-07ae8c80-06d2-11ea-87e8-e9d0ce863107.png)

fixed!
