### ISSUE TITLE
metadata: icon for nodes does not appear

### ISSUE THREAD

**Issue by hunchback** [skydive-project/skydive-ui#11]
![image](https://user-images.githubusercontent.com/2760739/68670557-e0cb4b80-0555-11ea-933d-2277a5c1006e.png)

**Comment by safchain** [comment]
oups forgot to fix this too, thanks

**Comment by safchain** [comment]
should be fix: https://github.com/skydive-project/skydive-ui/commit/ee86acb8952d94d4b844d920a91a5b872ec2de40

**Comment by hunchback** [comment]
still exists:

![image](https://user-images.githubusercontent.com/2760739/68844332-4cd2be80-06d2-11ea-901c-dbd3e5e1c82c.png)

**Comment by safchain** [comment]
![screenshot-0 0 0 0_8080-2019 11 14-10_36_11](https://user-images.githubusercontent.com/2663912/68844810-b058ee00-06ca-11ea-8c03-be1619b09481.png)
