### ISSUE TITLE
metadata: non-relevant field filters appear

### ISSUE THREAD

**Issue by hunchback** [skydive-project/skydive-ui#4]
![image](https://user-images.githubusercontent.com/2760739/68542298-f99bfb80-03b3-11ea-98a2-56fd5440f52e.png)

**Comment by hunchback** [comment]
The metadata filtering has many problems:

1. each time it goes back to default (Name, Type, MAC, Driver, State) while I would expect if I remove a field (such as State) is that it remembers that throughout the session (also when selecting other nodes)
2. I expect that the selection fields display are aligned with the context - for k8s the MAC field is not relevant and should not appear
3. there is no way to re-select the filter field which was removed (you must refresh the node selection) so visually maybe deselected fields should still be visible such that they can be re-selected (after being de-selected).

**Comment by safchain** [comment]
1. I will add the session handling in a short term, need to fix other things before
2. fixed: https://github.com/skydive-project/skydive-ui/commit/90c700fc61d0857adddd2487366b24c3807c1cc9
3: fixed: https://github.com/skydive-project/skydive-ui/commit/13cf79f7b507373e2a7f690e12fa103b5139f409

**Comment by safchain** [comment]
I would open a new issue for the first point, if that is ok for you and if the 2, 3 are fixed ?

**Comment by hunchback** [comment]
3. is fixed:

![image](https://user-images.githubusercontent.com/2760739/68670648-16703480-0556-11ea-9f60-707ca2b8238d.png)

**Comment by hunchback** [comment]
2. is fixed:

![image](https://user-images.githubusercontent.com/2760739/68670828-85e62400-0556-11ea-8b8b-581addca8c10.png)

![image](https://user-images.githubusercontent.com/2760739/68670857-93031300-0556-11ea-9b08-019f58b8744e.png)
