### ISSUE TITLE
metadata link: UUID title not meaningful 

### ISSUE THREAD

**Issue by hunchback** [skydive-project/skydive-ui#5]
![image](https://user-images.githubusercontent.com/2760739/68542908-6960b500-03b9-11ea-9458-4ec9278533e5.png)

**Comment by hunchback** [comment]
the title should rather be: <source-node>..<destination-node> so in this case:

```
default..minikube
```

**Comment by safchain** [comment]
the config file can be adapted for that puporse

**Comment by safchain** [comment]
Addressed by : https://github.com/skydive-project/skydive-ui/commit/7a262efca6aa0a96ee29103c0b7ccb288fdc259c

**Comment by hunchback** [comment]
![image](https://user-images.githubusercontent.com/2760739/68662185-03089d80-0545-11ea-9fe1-aad3cde0bf93.png)

**Comment by hunchback** [comment]
great ... also my personal preference would be lowercase ... but then again some would disagree (https://www.washingtonpost.com/technology/2019/11/04/move-fast-capitalize-things-facebook-unveils-new-logo/)
