### ISSUE TITLE
link type: selection options not clear

### ISSUE THREAD

**Issue by hunchback** [skydive-project/skydive-ui#6]
![image](https://user-images.githubusercontent.com/2760739/68543271-97e08f00-03bd-11ea-9bdb-e0d897f8e3cf.png)

**Comment by hunchback** [comment]
not clear what the default Link Type option means ... I suggest to only have two options (selected / not-selected).

**Comment by safchain** [comment]
I can add a tooltip, but I think that the 3 options make sense (not selected, on mouse over, selected) otherwise if selected it can be too crowded.

**Comment by hunchback** [comment]
I am not fond of tooltips ... maybe if the icon was clearer such as: https://cdn4.iconfinder.com/data/icons/cursors-gestures/100/click3-512.png
