### ISSUE TITLE
node grouping: just by type is not enough

### ISSUE THREAD

**Issue by hunchback** [skydive-project/skydive-ui#7]
![image](https://user-images.githubusercontent.com/2760739/68543894-b8ace280-03c5-11ea-8a4f-2ba0b1eaff39.png)

**Comment by safchain** [comment]
what do you suggest? can be configured through the config file

**Comment by hunchback** [comment]
grouping nodes according to type makes absolutely no sense; the correct grouping should be according to **type+namespace+labels**.  and in that case you may want the name of the composite node to be derived or generalized from names of all the participating nodes, such as using the common prefix. (as would work well for pods).

**Comment by safchain** [comment]
I won't say absolutely non sense, for ovsport VMs etc it does so depends on the use case and should be configured properly in the config file

**Comment by hunchback** [comment]
I have a PR addressing this https://github.com/skydive-project/skydive-ui/pull/10
