### ISSUE TITLE
node expansion: 5-node box is cumbersome

### ISSUE THREAD

**Issue by hunchback** [skydive-project/skydive-ui#8]
![image](https://user-images.githubusercontent.com/2760739/68544099-4be71780-03c8-11ea-8c1b-4184f1810696.png)

**Comment by hunchback** [comment]
note the secret(s) node which was expanded it groups 31 secret nodes and when expanded we get a 5-node box. this makes it very difficult to view/access a specific node. an alternative would be that the layer is extended so it can extend downwards:

so rather than:

```
secret(s): node1, node2, node3, node4, node5 ...
```

we would have:

```
secret(s)
```

and when expanded:

```
node1   node2   node3   node4   node5
node6   node7   node8   node9   node10
node11 node12 node13 node14 node15
node16 node17 node18 node19 node20
node21 node22 node23 node24 node25
node26 node27 node28 node29 node30
node31
```

**Comment by safchain** [comment]
the search box can be used to find the good one. we can fully expand. I won't develop at least in short term what you suggested as it will required a lot of modification

**Comment by hunchback** [comment]
![image](https://user-images.githubusercontent.com/2760739/68575093-07b15100-0474-11ea-8faa-fb7894c5da43.png)

**Comment by hunchback** [comment]
I only now noticed the `+` button which expands all. closing.
