### ISSUE TITLE
metadata: missing k8s fields

### ISSUE THREAD

**Issue by hunchback** [skydive-project/skydive-ui#9]
![image](https://user-images.githubusercontent.com/2760739/68544705-b56a2480-03ce-11ea-9145-2dc609052f88.png)

**Comment by hunchback** [comment]
Missing k8s specific fields such as `K8s.Namespace` and others

**Comment by hunchback** [comment]
Missing access to the extended k8s object

**Comment by safchain** [comment]
I can see that you have filters on the screenshot and not the k8s one that could the reason of this.

**Comment by hunchback** [comment]
![image](https://user-images.githubusercontent.com/2760739/68574466-9b821d80-0472-11ea-8bc6-21c6ac4d0d27.png)

**Comment by hunchback** [comment]
correct. closing
